<a href="https://colab.research.google.com/github/devikathampi/DriverDrowsinessDetection/blob/main/DriverDrowsiness1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math
import os.path
import csv
import glob
import tensorflow as tf
import h5py as h5py
from keras.preprocessing import image

In [ ]:
import imageio
import matplotlib.pyplot as plt
from mlxtend.image import extract_face_landmarks

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
! ls '/content/drive/My Drive/Dataset'

Fold1_part1


In [ ]:
def eye_aspect_ratio(eye):
	A = distance.euclidean(eye[1], eye[5])
	B = distance.euclidean(eye[2], eye[4])
	C = distance.euclidean(eye[0], eye[3])
	ear = (A + B) / (2.0 * C)
	return ear

In [ ]:
def mouth_aspect_ratio(mouth):
    A = distance.euclidean(mouth[14], mouth[18])
    C = distance.euclidean(mouth[12], mouth[16])
    mar = (A ) / (C)
    return mar

In [ ]:
def circularity(eye):
    A = distance.euclidean(eye[1], eye[4])
    radius  = A/2.0
    Area = math.pi * (radius ** 2)
    p = 0
    p += distance.euclidean(eye[0], eye[1])
    p += distance.euclidean(eye[1], eye[2])
    p += distance.euclidean(eye[2], eye[3])
    p += distance.euclidean(eye[3], eye[4])
    p += distance.euclidean(eye[4], eye[5])
    p += distance.euclidean(eye[5], eye[0])
    return 4 * math.pi * Area /(p**2)

In [ ]:
def mouth_over_eye(eye):
    ear = eye_aspect_ratio(eye)
    mar = mouth_aspect_ratio(eye)
    mouth_eye = mar/ear
    return mouth_eye

In [ ]:
def getFrame(sec):
    start = 180000
    vidcap.set(cv2.CAP_PROP_POS_MSEC, start + sec*1000)
    hasFrames,image = vidcap.read()
    return hasFrames, image

In [ ]:
# main program   
from scipy.spatial import distance
import cv2
data = []
labels = []
#for j in [60]:
  #for i in [10]:
vidcap = cv2.VideoCapture('drive/My Drive/Dataset/Fold1_part1/01/10.MOV')
sec = 0
frameRate = 1
success, image  = getFrame(sec)
count = 0
while success and count < 240: 
  landmarks = extract_face_landmarks(image)
  if sum(sum(landmarks)) != 0:
              count += 1
              data.append(landmarks)
              labels.append([i])
              sec = sec + frameRate
              sec = round(sec, 2)
              success, image = getFrame(sec)
              print(count)
  else:  
              sec = sec + frameRate
              sec = round(sec, 2)
              success, image = getFrame(sec)
              print("not detected")

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


/usr/local/lib/python3.7/dist-packages/mlxtend/image/extract_face_landmarks.py:61: UserWarning: No face detected.
  warnings.warn('No face detected.')


not detected
21
22
23
24
25
26
27
28
29
not detected
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240


In [ ]:
data = np.array(data)
labels = np.array(labels)
print(data)

[[[355 717]
  [357 762]
  [362 807]
  ...
  [567 840]
  [556 841]
  [544 840]]

 [[400 687]
  [398 730]
  [398 774]
  ...
  [605 811]
  [591 810]
  [577 808]]

 [[375 704]
  [372 748]
  [375 791]
  ...
  [581 820]
  [567 820]
  [553 819]]

 ...

 [[363 745]
  [368 784]
  [377 823]
  ...
  [564 818]
  [549 821]
  [535 822]]

 [[365 741]
  [370 781]
  [379 820]
  ...
  [565 818]
  [550 821]
  [536 822]]

 [[371 737]
  [377 777]
  [385 817]
  ...
  [582 817]
  [567 820]
  [553 821]]]


In [ ]:
features = []
for d in data:
  eye = d[36:68]
  ear = eye_aspect_ratio(eye)
  mar = mouth_aspect_ratio(eye)
  cir = circularity(eye)
  mouth_eye = mouth_over_eye(eye)
  features.append([ear, mar, cir, mouth_eye])

In [ ]:
features = np.array(features)
features.shape

(240, 4)

In [ ]:
data.shape

(240, 68, 2)

In [ ]:
labels.shape

(240, 1)

In [ ]:
np.save(open('Data_60_10.npy', 'wb'),data)
np.save(open('Fold1_part1_features_60_10.npy', 'wb'),features)
np.save(open('Fold1_part1_labels_60_10.npy', 'wb'),labels)
np.savetxt("Fold1_part1_features_60_10.csv", features, delimiter = ",")
np.savetxt("Fold1_part1_labels_60_10.csv", labels, delimiter = ",")

In [ ]:
a = np.load('Data_60_10.npy')
b = np.load('Fold1_part1_features_60_10.npy')
c = np.load('Fold1_part1_labels_60_10.npy')

In [ ]:
import pandas as pd
file = pd.read_csv('Fold1_part1_features_60_10.csv',header=None)
file.columns=['EAR','MAR','PUC','MOE']
file.head(50)

EAR       MAR       PUC       MOE
0   0.353448  0.738151  0.484876  2.088427
1   0.323479  0.758340  0.480260  2.344327
2   0.246202  0.794358  0.383417  3.226449
3   0.346352  0.616346  0.514844  1.779537
4   0.298201  0.615636  0.436632  2.064496
5   0.240591  0.665694  0.380255  2.766915
6   0.217319  0.548215  0.390604  2.522633
7   0.319579  0.641870  0.488472  2.008486
8   0.330352  0.728127  0.460319  2.204096
9   0.304126  0.708808  0.435336  2.330642
10  0.306713  0.743135  0.461784  2.422897
11  0.204808  0.709200  0.361039  3.462758
12  0.343301  0.695755  0.497302  2.026658
13  0.289363  0.725564  0.451408  2.507451
14  0.271529  0.726757  0.425512  2.676531
15  0.335618  0.672739  0.505985  2.004481
16  0.336341  0.655252  0.457015  1.948181
17  0.335054  0.702551  0.503930  2.096828
18  0.284643  0.762206  0.387694  2.677765
19  0.211029  0.554971  0.308632  2.629835
20  0.272555  0.710341  0.421060  2.606230
21  0.303816  0.870306  0.426547  2.864587
22  0.303174  0.818968  0.426802  2.701316
23  0.322847  0.738961  0.475662  2.288888
24  0.317353  0.757842  0.452952  2.388008
25  0.280456  0.771194  0.411592  2.749789
26  0.315976  0.776597  0.455836  2.457772
27  0.291635  0.756969  0.386956  2.595607
28  0.302268  0.763514  0.455142  2.525947
29  0.209306  0.707485  0.381513  3.380146
30  0.286272  0.719962  0.426025  2.514961
31  0.313390  0.756950  0.463611  2.415363
32  0.271827  0.751479  0.424368  2.764546
33  0.280559  0.767187  0.424524  2.734488
34  0.272210  0.825197  0.383152  3.031469
35  0.222876  0.781220  0.364811  3.505183
36  0.281332  0.804271  0.430052  2.858799
37  0.281883  0.777974  0.410084  2.759916
38  0.319422  0.767526  0.464612  2.402857
39  0.244523  0.811866  0.363367  3.320207
40  0.343874  0.780153  0.488045  2.268716
41  0.328587  0.781725  0.511035  2.379047
42  0.336794  0.764502  0.503266  2.269942
43  0.344051  0.795866  0.491147  2.313221
44  0.329717  0.801272  0.459653  2.430179
45  0.293818  0.784735  0.435836  2.670816
46  0.326652  0.785371  0.454837  2.404308
47  0.299051  0.784533  0.449032  2.623410
48  0.303666  0.802773  0.415561  2.643603
49  0.279425  0.792659  0.438303  2.836754

In [ ]:
file.to_csv('features1.csv',index=False)

In [ ]:
df = pd.read_csv('features1.csv')
print(df)

          EAR       MAR       PUC       MOE
0    0.353448  0.738151  0.484876  2.088427
1    0.323479  0.758340  0.480260  2.344327
2    0.246202  0.794358  0.383417  3.226449
3    0.346352  0.616346  0.514844  1.779537
4    0.298201  0.615636  0.436632  2.064496
..        ...       ...       ...       ...
235  0.300739  0.797325  0.436028  2.651222
236  0.313246  0.790945  0.465389  2.524995
237  0.279668  0.815843  0.430749  2.917181
238  0.300905  0.804894  0.453738  2.674906
239  0.299942  0.808788  0.429992  2.696478

[240 rows x 4 columns]


In [ ]:
df['Participant'] = 1.0
df.head()

EAR       MAR       PUC       MOE  Participant
0  0.353448  0.738151  0.484876  2.088427          1.0
1  0.323479  0.758340  0.480260  2.344327          1.0
2  0.246202  0.794358  0.383417  3.226449          1.0
3  0.346352  0.616346  0.514844  1.779537          1.0
4  0.298201  0.615636  0.436632  2.064496          1.0

In [ ]:
df['Y']=0.0

In [ ]:
df.head()

EAR       MAR       PUC       MOE  Participant    Y
0  0.353448  0.738151  0.484876  2.088427          1.0  0.0
1  0.323479  0.758340  0.480260  2.344327          1.0  0.0
2  0.246202  0.794358  0.383417  3.226449          1.0  0.0
3  0.346352  0.616346  0.514844  1.779537          1.0  0.0
4  0.298201  0.615636  0.436632  2.064496          1.0  0.0

In [ ]:
df_total = df
cols = df_total.columns.tolist()
cols = cols[-1:] + cols[3:4] + cols[4:5] + cols[:3]
df_total = df_total[cols]
df_total.to_csv("Features2.csv")
df_total

Y       MOE  Participant       EAR       MAR       PUC
0    0.0  2.088427          1.0  0.353448  0.738151  0.484876
1    0.0  2.344327          1.0  0.323479  0.758340  0.480260
2    0.0  3.226449          1.0  0.246202  0.794358  0.383417
3    0.0  1.779537          1.0  0.346352  0.616346  0.514844
4    0.0  2.064496          1.0  0.298201  0.615636  0.436632
..   ...       ...          ...       ...       ...       ...
235  0.0  2.651222          1.0  0.300739  0.797325  0.436028
236  0.0  2.524995          1.0  0.313246  0.790945  0.465389
237  0.0  2.917181          1.0  0.279668  0.815843  0.430749
238  0.0  2.674906          1.0  0.300905  0.804894  0.453738
239  0.0  2.696478          1.0  0.299942  0.808788  0.429992

[240 rows x 6 columns]

In [ ]:
t = df_total.drop_duplicates("Participant")
df_total = df_total[~df_total.Participant.isin(t[t.Y > 0].Participant)]
df_total.shape

(240, 6)

In [ ]:
df_means = df_total.groupby("Participant")["EAR","MAR","PUC","MOE"].mean()
df_std = df_total.groupby("Participant")["EAR","MAR","PUC","MOE"].std()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  


In [ ]:
#Functions for mean and std for each feature
def mean_EAR(respondent):
    return df_means.loc[respondent]["EAR"]

def mean_MAR(respondent):
    return df_means.loc[respondent]["MAR"]

def mean_Circularity(respondent):
    return df_means.loc[respondent]["PUC"]

def mean_MOE(respondent):
    return df_means.loc[respondent]["MOE"]


def std_EAR(respondent):
    return df_std.loc[respondent]["EAR"]

def std_MAR(respondent):
    return df_std.loc[respondent]["MAR"]

def std_Circularity(respondent):
    return df_std.loc[respondent]["PUC"]

def std_MOE(respondent):
    return df_std.loc[respondent]["MOE"]

In [ ]:
df_total["EAR_mean"] = df_total["Participant"].apply(mean_EAR)
df_total["MAR_mean"] = df_total["Participant"].apply(mean_MAR)
df_total["Circularity_mean"] = df_total["Participant"].apply(mean_Circularity)
df_total["MOE_mean"] = df_total["Participant"].apply(mean_MOE)

df_total["EAR_std"] = df_total["Participant"].apply(std_EAR)
df_total["MAR_std"] = df_total["Participant"].apply(std_MAR)
df_total["Circularity_std"] = df_total["Participant"].apply(std_Circularity)
df_total["MOE_std"] = df_total["Participant"].apply(std_MOE)

In [ ]:
df_total.head()

Y       MOE  Participant  ...  MAR_std  Circularity_std   MOE_std
0  0.0  2.088427          1.0  ...  0.05369         0.039511  0.424904
1  0.0  2.344327          1.0  ...  0.05369         0.039511  0.424904
2  0.0  3.226449          1.0  ...  0.05369         0.039511  0.424904
3  0.0  1.779537          1.0  ...  0.05369         0.039511  0.424904
4  0.0  2.064496          1.0  ...  0.05369         0.039511  0.424904

[5 rows x 14 columns]

In [ ]:
#Calculating normalised features for each row in the original dataframe
df_total["EAR_N"] = (df_total["EAR"]-df_total["EAR_mean"])/ df_total["EAR_std"]
df_total["MAR_N"] = (df_total["MAR"]-df_total["MAR_mean"])/ df_total["MAR_std"]
df_total["Circularity_N"] = (df_total["PUC"]-df_total["Circularity_mean"])/ df_total["Circularity_std"]
df_total["MOE_N"] = (df_total["MOE"]-df_total["MOE_mean"])/ df_total["MOE_std"]

In [ ]:
df_total.to_csv('totalwithallinfo.csv',index=False)

In [ ]:
df_main = df_total.drop(["EAR_mean","MAR_mean","Circularity_mean","MOE_mean","EAR_std","MAR_std","Circularity_std","MOE_std"],axis=1)
df_main.to_csv('totalwithmaininfo.csv',index=False)

In [ ]:
df_total.head()

Y       MOE  Participant  ...     MAR_N  Circularity_N     MOE_N
0  0.0  2.088427          1.0  ... -0.844272       1.113735 -1.342629
1  0.0  2.344327          1.0  ... -0.468235       0.996921 -0.740374
2  0.0  3.226449          1.0  ...  0.202611      -1.454124  1.335674
3  0.0  1.779537          1.0  ... -3.112954       1.872207 -2.069592
4  0.0  2.064496          1.0  ... -3.126176      -0.107288 -1.398949

[5 rows x 18 columns]

In [ ]:
df_main.head()

Y       MOE  Participant  ...     MAR_N  Circularity_N     MOE_N
0  0.0  2.088427          1.0  ... -0.844272       1.113735 -1.342629
1  0.0  2.344327          1.0  ... -0.468235       0.996921 -0.740374
2  0.0  3.226449          1.0  ...  0.202611      -1.454124  1.335674
3  0.0  1.779537          1.0  ... -3.112954       1.872207 -2.069592
4  0.0  2.064496          1.0  ... -3.126176      -0.107288 -1.398949

[5 rows x 10 columns]